spring:
  #    profiles:
  #      active: local
  application:
    name: course-service

  datasource:
    url: jdbc:mysql://5.189.154.210:3306/eldt_db?useUnicode=true&characterEncoding=UTF-8&createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: winggsak123
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5

  jpa:
    show-sql: true
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
    properties:
      #        javax.persistence.sharedCache.mode: ENABLE_SELECTIVE
      hibernate:
        #Hibernate Full Text search
        dialect: org.hibernate.dialect.MySQL8Dialect
        type: trace
        dialect.storage_engine: innodb
      hibernate.search:
        backend:
          type: lucene
          lucene_version: LATEST
          analysis.configurer: luceneAnalysisConfiguration
          directory.root: opt/indexes
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus, scheduledtasks

server:
  port: 8090
  forward-headers-strategy: framework
  error:
    include-message: always
  http2:
    enabled: true
  tomcat:
    threads:
      max: 5
      min-spare: 1
common:
  converter:
    destination-dir: /converted/
  media:
    path: https://eldtinc.com/uploads/
#    path: http://localhost:8090/uploads/
security:
  jwt:
    tokenIssuer: https://eldtinc.com/
    tokenSigningKey: dev-secret-key-to-be-used-should-be-512-bit-at-least-otherwise-it-will-just-fail
    tokenExpirationTime: 30 # Minutes
stripe:
  credentials:
    secret-key: sk_test_51KhKOBEMKimteY1OeDYmUJY2DUF9yMS4O9Dtxm89RtiyQgSbg5vZK5LS8GiuTv9DUthwKmzhmpYxbAQlDbryZgX100Zthn1y8t
    public-key: pk_test_51KhKOBEMKimteY1Oo9yVQSmKtcnxTDxfAT1ylyAR3SCHUJT2ka2GjXN96sUbCggnFR3EDafE3E02IyKfnhWvBZkG00QvafGxmP